# Higgs Boson - Predicting

(example from xgboost docs)

## [Link](https://www.kaggle.com/c/higgs-boson)

In [10]:
import numpy as np
import xgboost as xgb
import pandas as pd

In [7]:
modelfile = 'higgs.model'
threshold_ratio = 0.15

In [3]:
dtest = np.loadtxt('data/higgs/test.csv', delimiter=',', skiprows=1 )
data   = dtest[:,1:31]
idx = dtest[:,0]

Predict!

In [4]:
xgmat = xgb.DMatrix( data, missing = -999.0 )
bst = xgb.Booster({'nthread':16}, model_file = modelfile)
ypred = bst.predict( xgmat )

In [5]:
res  = [ ( int(idx[i]), ypred[i] ) for i in range(len(ypred)) ]

rorder = {}
for k, v in sorted( res, key = lambda x:-x[1] ):
    rorder[ k ] = len(rorder) + 1

In [9]:
ntop = int( threshold_ratio * len(rorder ) )
fo = open('higgs.pred.csv', 'w')
nhit = 0
ntot = 0
fo.write('EventId,RankOrder,Class\n')
for k, v in res:
    if rorder[k] <= ntop:
        lb = 's'
        nhit += 1
    else:
        lb = 'b'
    # change output rank order to follow Kaggle convention
    fo.write('%s,%d,%s\n' % ( k,  len(rorder)+1-rorder[k], lb ) )
    ntot += 1
fo.close()

In [11]:
pd.read_csv('higgs.pred.csv')

        EventId  RankOrder Class
0        350000      12429     b
1        350001     239692     b
2        350002     351852     b
3        350003     492038     s
4        350004      93743     b
5        350005     155334     b
6        350006     202380     b
7        350007      31079     b
8        350008      97704     b
9        350009     496777     s
10       350010     150278     b
11       350011     208182     b
12       350012     373279     b
13       350013     237856     b
14       350014      34334     b
15       350015      35523     b
16       350016     204430     b
17       350017      56520     b
18       350018     132555     b
19       350019     432850     b
20       350020     155321     b
21       350021      73254     b
22       350022     247038     b
23       350023     142407     b
24       350024     195399     b
25       350025     427873     b
26       350026     400131     b
27       350027     294902     b
28       350028     236052     b
29       350029     218341     b
...         ...        ...   ...
549970   899970      49163     b
549971   899971     349120     b
549972   899972     463892     b
549973   899973     393177     b
549974   899974     203520     b
549975   899975     347694     b
549976   899976     244794     b
549977   899977     108047     b
549978   899978      75624     b
549979   899979      53464     b
549980   899980      33946     b
549981   899981      77760     b
549982   899982     209015     b
549983   899983     321267     b
549984   899984      93681     b
549985   899985      64031     b
549986   899986     434788     b
549987   899987     370026     b
549988   899988     465584     b
549989   899989     103927     b
549990   899990     260974     b
549991   899991     134009     b
549992   899992     453636     b
549993   899993      71280     b
549994   899994      46185     b
549995   899995     123088     b
549996   899996     380470     b
549997   899997      83269     b
549998   899998     402369     b
549999   899999     254634     b

[550000 rows x 3 columns]